# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solving the MDP using value iteration algorithm.
#'
#' @param paramModel parameters a list created using \code{\link{setParameters}}.
#'
#' @return A list
#' @export
SolveMDPModel <- function(paramModel) {
    .Call('mdpTillage_SolveMDPModel', PACKAGE = 'mdpTillage', paramModel)
}

